baseURL = "https://emergency.neverfapdeluxe.com/"
title = "NeverFap Deluxe Emergency | The World's Most Comprehensive Porn Addiction Recovery Platform."
languageCode = "en-us"
theme = "emergency_theme"

enableRobotsTXT = true
canonifyURLs = true

// TODO
googleAnalytics = ""

